### ISSUE TITLE
Logged Queries' Parameters' are Missing their Paired Value

### ISSUE THREAD

**Issue by Bubinga** [hryz/Dapper.Logging#15]
I am using this library in a .Net 5, Blazor, and Serilog environment. My setup is as follows:
```c#
Startup.cs:
services.AddDbConnectionFactory(prv => new MySqlConnection(Configuration.GetConnectionString("DataDB")),
                                null, ServiceLifetime.Singleton);
services.AddSingleton<IDataAccess, DataAccess>();
```
I use made a DataAccess class to clean up code for repeated query structures. 
```c#
namespace DataAccessLibrary.DataAccess
{
    public class DataAccess : IDataAccess
    {
        private readonly IDbConnectionFactory connectionFactory;
        public DataAccess(IDbConnectionFactory _connectionFactory)
        {
            connectionFactory = _connectionFactory;
        }
        public async Task<T> LoadDataSingle<T, U>(string sql, U parameters)
        {
            using (IDbConnection connection = connectionFactory.CreateConnection())
            {
                var row = await connection.QueryFirstOrDefaultAsync<T>(sql, parameters);
                return row;
            }
        }
    }
}
```
The error comes when I do a parameterized query like the following. The example is provided in a Blazor file, but it not specific to that situtation:
```c#
@page "/Test" 
@using DataAccessLibrary.DataAccess 
@inject IDataAccess data 

<h1>@title</h1>

@code { 
    DateTime Date = new DateTime(2020, 6, 4);
    string title;
    protected override async Task OnInitializedAsync()
    {
        string getEventsFromDate = "SELECT e.Title FROM example e WHERE e.Date = @date";
        title = await data.LoadDataSingle<string, dynamic>(getEventsFromDate, new { date = Date.ToString("yyyy-MM-dd") });
    }
}
```
When this query is logged it returns:

> [13:09:30 INF] Dapper connection: open, elapsed: 2 ms, context: {"$type": "Empty"}, connection: {"$type": "Empty"}
[13:09:30 INF] Dapper query:
SELECT e.Title FROM example e WHERE e.Date = @date
Parameters: {"date": "?"}, elapsed: 6 ms, context: {"$type": "Empty"}, connection: {"$type": "Empty"}
[13:09:30 INF] Dapper connection: close, elapsed: 0 ms, context: {"$type": "Empty"}, connection: {"$type": "Empty"}

It is correctly picking up the name of the parameter, but not picking up it's value. It should be

>Parameters: {"date": "2020-06-04"} instead of Parameters: {"date": "?"}

**Comment by matyasbach** [comment]
You need to turn on SensitiveDataLogging:
```C#
services.AddDbConnectionFactory(prv => new MySqlConnection(Configuration.GetConnectionString("DataDB")),
                                config => config.WithSensitiveDataLogging(), ServiceLifetime.Singleton);
```

**Comment by hryz** [comment]
@matyasbach is right. Logging the values of the parameters is disabled by default (just like in EF Core) for security reasons. Most people don't want Personal Identifiable Information or credit card numbers or passwords in their logs.
