### ISSUE TITLE
Strong naming

### ISSUE THREAD

**Issue by pnmcosta** [hryz/Dapper.Logging#7]
Hi @hryz,

Me again, sorry, any chance you can strong name the package?

`3>CSC : warning CS8002: Referenced assembly 'Dapper.Logging, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Unfortunately we require it for our dependencies and it completely slipped me before.

Thanks,
P.

**Comment by hryz** [comment]
Hello @pnmcosta ,

To be honest, I thought that strong naming and binding redirects are in the past.
Let me investigate the possible downsides of  signing the package.
I hope I’ll have some time for this till the weekend.

**Comment by pnmcosta** [comment]
Not in full framework unfortunately, but we do sign all our .net standard and core's too. It's a firm policy, i guess from the past 😂 

Thanks man, really appreciate it.

All the best,

Cheers,
P.

**Comment by pnmcosta** [comment]
Perfect, thank you so much :)
